### ISSUE TITLE
Scrollbar only functions while the mouse cursor is above the widget

### ISSUE THREAD

**Issue by bmeznarsic** [solus-project/brisk-menu#3]
Enable the user to drag the scrollbar with their mouse even if the mouse cursor is not over the widget.

**Comment by ikeydoherty** [comment]
Yep - down to our grab stuff. Gonna need a bit of working out :)

**Comment by ikeydoherty** [comment]
OK investigated this further, seems GTK3 specific:

https://bugzilla.gnome.org/show_bug.cgi?id=782870

**Comment by ikeydoherty** [comment]
Just confirmed that the 2 upstream patches to GTK on the linked bug actually fix this =)

**Comment by ikeydoherty** [comment]
This is fixed in GTK 3.22.18 and isn't Brisk-specific - please ensure your distributions either update to latest GTK version or backport the commits for that bug:

https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=9b032073cbcf5aadbeb4b74f0cf662a9fa5f5530
https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=54c26e0983b9300d3bc66adf05cf668e7a1bfe86
