### ISSUE TITLE
Does not support the right-to-left direction

### ISSUE THREAD

**Issue by zakariakov** [solus-project/brisk-menu#57]

**Comment by ikeydoherty** [comment]
Gonna need more details than that or I'm going to close the issue.

**Comment by flexiondotorg** [comment]
I think they might be referring to right-to-left language support.

**Comment by ikeydoherty** [comment]
Gathered that, still need more details. i.e. what *doesn't* it do right. Boxes are ordered by GTK so I know it'll swap the sidebar with the main view

**Comment by husaination** [comment]
I'm having an issue related to this subject, I have two input sources (English and Arabic) and when my computer gets locked and I have to type in the password, I sometimes find the cursor direction is from right to left which is not good because when I type the password from right to left Solus says it's wrong, and I can't even change the input source from the keyboard, it just doesn't work in the login screen, thank you.

**Comment by ikeydoherty** [comment]
While that is an issue (with `lightdm-gtk-greeter`) it's not related to this issue @husaination. For your issue I recommend using `slick-greeter`.

I'm closing this issue per my first comment. We have translations nowadays so .. ya. :)

**Comment by zakariakov** [comment]
thank you very much
The window from right to left is well displayed
very good

![brisk-screen](https://user-images.githubusercontent.com/25525273/32405339-5efb4348-c15b-11e7-9a27-477a94cb660e.png)
