### ISSUE TITLE
[Feature Request]  Make possible to resize the menu

### ISSUE THREAD

**Issue by Huluti** [solus-project/brisk-menu#7]
It would be great if we can resize the menu. On large screens, it look a bit small. Keep up the great work guys, it is already very great!

**Comment by ThanosApostolou** [comment]
It is indeed really necessary, especially for us who like to use Application font size 12 or bigger. The "Control Center" pinned shorcut is already half-hidden and I cannot add pinned shortcuts without needing to scroll down in order to use them :disappointed: See screenshot:
![screenshot at 2017-06-10 02-02-00](https://user-images.githubusercontent.com/21288843/26997362-c1cbb29e-4d81-11e7-8073-a07c52cf8c2d.png)

**Comment by bwat47** [comment]
IMO this would be nice to have, as the auto resize feature doesn't always seem to work 100% properly (e.g. https://github.com/solus-project/brisk-menu/issues/83)
